# Generated by Django 6.1.1 on 2026-09-19 06:52

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='slug')),
                ('summary', models.CharField(max_length=250, verbose_name='summary')),
                ('description', models.TextField(max_length=5000, verbose_name='detailed description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/%Y/%m/', validators=[accounts.validators.validate_image_file], verbose_name='cover image')),
                ('demo_url', models.URLField(blank=True, verbose_name='demo URL')),
                ('repo_url', models.URLField(blank=True, verbose_name='repository URL')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords e.g. python, react, machine-learning', max_length=200, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='unique_project_like')],
            },
        ),
    ]
