# Generated by Django 6.1.1 on 2026-09-19 06:52

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='slug')),
                ('category', models.CharField(choices=[('community', 'Community / Club'), ('creator', 'Creator / Artist'), ('technology', 'Tech & Open Source'), ('business', 'Business & Brand'), ('education', 'Education & Research')], default='community', max_length=50, verbose_name='category')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='description')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pages/avatars/%Y/%m/', validators=[accounts.validators.validate_image_file], verbose_name='avatar')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages/covers/%Y/%m/', validators=[accounts.validators.validate_image_file], verbose_name='cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='pages.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('page', 'user'), name='unique_page_follower')],
            },
        ),
    ]
