# Generated by Django 6.1.1 on 2026-09-19 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(max_length=50, verbose_name='target type')),
                ('target_id', models.PositiveIntegerField(verbose_name='target id')),
                ('reason', models.CharField(choices=[('spam', 'Spam or Scam'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('violence', 'Violence or Dangerous Content'), ('copyright', 'Copyright Violation'), ('other', 'Other')], max_length=50, verbose_name='reason')),
                ('details', models.TextField(blank=True, max_length=1000, verbose_name='details')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed & Actioned'), ('dismissed', 'Dismissed')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relations', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked_user'), name='unique_user_block'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked_user')), _negated=True), name='prevent_self_block')],
            },
        ),
    ]
